apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: controle-agua-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: controle-agua-frontend:v1.0.5
        ports:
        - containerPort: 80
