apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: controle-agua-teste
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: controle-agua-db:v1.0.0
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "agua_intake"
        - name: POSTGRES_USER
          value: "admin"
        - name: POSTGRES_PASSWORD
          value: "admin123"
