FROM python:3.9-slim

WORKDIR /app/backend

ENV FLASK_APP=app.py

RUN apt-get update && \
    apt-get install -y postgresql-client && \
    rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install flask
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["flask", "run", "-h", "0.0.0.0", "-p", "5000"]
